### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by somedevreally** [angristan/feedbin-docker#1]
Hi,
i did all the changes to env and docker-config and every is up and running.
when i go to feedbin_web url which is my lan ip it give an error
```
Action Controller: Exception caught
Blocked host: x.x.x.x
To allow requests to xx.x.x, add the following to your environment configuration:
config.hosts << "x.x.x.x"
```

**Comment by angristan** [comment]
You seem to be missing `FEEDBIn_HOST`.

**Comment by somedevreally** [comment]
in .env under # Rails
`FEEDBIN_HOST=x.x.x.x:port
`
is set
should it be set some other files too?

**Comment by angristan** [comment]
No, only here

**Comment by angristan** [comment]
`FEEDBIN_HOST` should not have the port

**Comment by somedevreally** [comment]
ok i removed the port, now i see this error on feedbib_web console
`
2020-02-12 18:19:02 +0000: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>`

**Comment by angristan** [comment]
Oh yeah that was one of the PR I made for Feedbin. If you're running as localhost without HTTPS, set `FORCE_SSL=false`, I forgot to add it (https://github.com/angristan/feedbin-docker/commit/6d0a06d5ef2eaf1fd5bb5b7b18a9143c5e16c978)

**Comment by somedevreally** [comment]
ok added `FORCE_SSL=false` but it still redirects to https, deleted and created the container

**Comment by angristan** [comment]
that probably means the redirection has been cached by your browser

**Comment by somedevreally** [comment]
ok finally, thanks.
now on signup page when i try to create new user, after submitting it goes x.x.x.x/users and its blank page

**Comment by angristan** [comment]
I have no idea. Looks Redis related so make sure it is up and running and you didn't modify the redis url.

**Comment by somedevreally** [comment]
Redis log
```
1:C 13 Feb 2020 13:55:20.446 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 13 Feb 2020 13:55:20.446 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 13 Feb 2020 13:55:20.446 # Configuration loaded
1:M 13 Feb 2020 13:55:20.450 * Running mode=standalone, port=6379.
1:M 13 Feb 2020 13:55:20.450 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 13 Feb 2020 13:55:20.450 # Server initialized
1:M 13 Feb 2020 13:55:20.450 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 13 Feb 2020 13:55:20.450 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 13 Feb 2020 13:55:20.704 * DB loaded from append only file: 0.253 seconds
1:M 13 Feb 2020 13:55:20.704 * Ready to accept connections
```
can we create login at backend?

**Comment by angristan** [comment]
No. But if I'm not mistaken in your previous message you didn't post the full log trace.

**Comment by somedevreally** [comment]
thats start to blank page

feedbin_web log
  ```
=> Booting Puma
=> Rails 6.0.2.1 application starting in production 
=> Run `rails server --help` for more startup options
I, [2020-02-13T21:14:05.746129 #1]  INFO -- honeybadger: ** [Honeybadger] Initializing Honeybadger Error Tracker for Ruby. Ship it! version=4.5.6 framework=rails level=1 pid=1
Puma starting in single mode...
* Version 4.3.1 (ruby 2.6.5-p114), codename: Mysterious Traveller
* Min threads: 5, max threads: 5
* Environment: production
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
F, [2020-02-13T21:14:24.848422 #1] FATAL -- :   
ArgumentError (wrong number of arguments (given 4, expected 3)):
redis (4.1.3) lib/redis.rb:819:in `setex'
/usr/local/lib/ruby/2.6.0/delegate.rb:83:in `method_missing'
rack-attack (6.2.2) lib/rack/attack/store_proxy/redis_store_proxy.rb:19:in `block in write'
rack-attack (6.2.2) lib/rack/attack/store_proxy/redis_proxy.rb:49:in `rescuing'
rack-attack (6.2.2) lib/rack/attack/store_proxy/redis_store_proxy.rb:19:in `write'
rack-attack (6.2.2) lib/rack/attack/cache.rb:63:in `do_count'
rack-attack (6.2.2) lib/rack/attack/cache.rb:21:in `count'
rack-attack (6.2.2) lib/rack/attack/throttle.rb:31:in `matched_by?'
rack-attack (6.2.2) lib/rack/attack.rb:101:in `block in throttled?'
rack-attack (6.2.2) lib/rack/attack.rb:100:in `any?'
rack-attack (6.2.2) lib/rack/attack.rb:100:in `throttled?'
/usr/local/lib/ruby/2.6.0/forwardable.rb:230:in `throttled?'
rack-attack (6.2.2) lib/rack/attack.rb:166:in `call'
rack (4ebd70b243d7) lib/rack/content_length.rb:17:in `call'
rack (4ebd70b243d7) lib/rack/tempfile_reaper.rb:17:in `call'
rack (4ebd70b243d7) lib/rack/etag.rb:27:in `call'
rack (4ebd70b243d7) lib/rack/conditional_get.rb:40:in `call'
rack (4ebd70b243d7) lib/rack/head.rb:14:in `call'
rails (04e08ee17fb8) actionpack/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (4ebd70b243d7) lib/rack/session/abstract/id.rb:269:in `context'
rack (4ebd70b243d7) lib/rack/session/abstract/id.rb:263:in `call'
rails (04e08ee17fb8) actionpack/lib/action_dispatch/middleware/cookies.rb:647:in `call'
rails (04e08ee17fb8) actionpack/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
rails (04e08ee17fb8) activesupport/lib/active_support/callbacks.rb:101:in `run_callbacks'
rails (04e08ee17fb8) actionpack/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
rails (04e08ee17fb8) actionpack/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
rails (04e08ee17fb8) actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
rails (04e08ee17fb8) actionpack/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
lograge (0.11.2) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
rails (04e08ee17fb8) railties/lib/rails/rack/logger.rb:28:in `call'
rails (04e08ee17fb8) actionpack/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
rails (04e08ee17fb8) actionpack/lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (4ebd70b243d7) lib/rack/method_override.rb:24:in `call'
rack (4ebd70b243d7) lib/rack/runtime.rb:24:in `call'
rails (04e08ee17fb8) activesupport/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
rails (04e08ee17fb8) actionpack/lib/action_dispatch/middleware/executor.rb:14:in `call'
rails (04e08ee17fb8) actionpack/lib/action_dispatch/middleware/static.rb:126:in `call'
rack (4ebd70b243d7) lib/rack/sendfile.rb:113:in `call
rails (04e08ee17fb8) actionpack/lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
honeybadger (4.5.6) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
honeybadger (4.5.6) lib/honeybadger/agent.rb:397:in `with_rack_env'
honeybadger (4.5.6) lib/honeybadger/rack/error_notifier.rb:30:in `call'
honeybadger (4.5.6) lib/honeybadger/rack/user_feedback.rb:31:in `call'
honeybadger (4.5.6) lib/honeybadger/rack/user_informer.rb:21:in `call'
rails (04e08ee17fb8) railties/lib/rails/engine.rb:527:in `call'
rails (04e08ee17fb8) railties/lib/rails/railtie.rb:190:in `public_send'
rails (04e08ee17fb8) railties/lib/rails/railtie.rb:190:in `method_missing'
puma (4.3.1) lib/puma/configuration.rb:228:in `call'
puma (4.3.1) lib/puma/server.rb:681:in `handle_request'
puma (4.3.1) lib/puma/server.rb:472:in `process_client'
puma (4.3.1) lib/puma/server.rb:328:in `block in run'
puma (4.3.1) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
E, [2020-02-13T21:14:24.861581 #1] ERROR -- honeybadger: ** [Honeybadger] Unable to send error report: API key is missing. id=6c3045da-9209-xxxx-xxxx-5edf3xa2977 level=3 pid=1
```

**Comment by ldexterldesign** [comment]
👋 https://github.com/angristan/feedbin-docker/issues/6
