### ISSUE TITLE
cannot run database migrations

### ISSUE THREAD

**Issue by kzshantonu** [angristan/feedbin-docker#96]
```
/usr/local/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/usr/local/bundle/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/usr/local/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/usr/local/bundle/gems/net-protocol-0.1.3/lib/net/protocol.rb:208: warning: previous definition of BUFSIZE was here
/usr/local/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/usr/local/bundle/gems/net-protocol-0.1.3/lib/net/protocol.rb:504: warning: previous definition of Socket was here
/app/config/initializers/core_ext/clean.rb:19: warning: Skipping set of ruby2_keywords flag for clean (method accepts keywords or method does not accept argument splat)
/app/config/initializers/sidekiq.rb:7: warning: Sidekiq's Delayed Extensions will be removed in Sidekiq 7.0
rake aborted!
ArgumentError: Secret should not be nil.
/usr/local/bundle/gems/activesupport-7.0.2.2/lib/active_support/message_verifier.rb:111:in `initialize'
/usr/local/bundle/gems/activesupport-7.0.2.2/lib/active_support/messages/rotator.rb:7:in `initialize'
/app/app/jobs/safari_push_notification_send.rb:5:in `new'
/app/app/jobs/safari_push_notification_send.rb:5:in `<class:SafariPushNotificationSend>'
/app/app/jobs/safari_push_notification_send.rb:1:in `<main>'
/usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:237:in `block (2 levels) in eager_load'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `each'
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `eager_load_all'
/usr/local/bundle/gems/railties-7.0.2.2/lib/rails/application/finisher.rb:78:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-7.0.2.2/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-7.0.2.2/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-7.0.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
/usr/local/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each'
/usr/local/lib/ruby/2.7.0/tsort.rb:347:in `call'
/usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
/usr/local/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
/usr/local/bundle/gems/railties-7.0.2.2/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-7.0.2.2/lib/rails/application.rb:372:in `initialize!'
/app/config/environment.rb:5:in `<main>'
/app/lib/tasks/feedbin_generate_coupon.rake:2:in `require_relative'
/app/lib/tasks/feedbin_generate_coupon.rake:2:in `<main>'
/usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/usr/local/bundle/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/usr/local/bundle/gems/railties-7.0.2.2/lib/rails/engine.rb:661:in `block in run_tasks_blocks'
/usr/local/bundle/gems/railties-7.0.2.2/lib/rails/engine.rb:661:in `each'
/usr/local/bundle/gems/railties-7.0.2.2/lib/rails/engine.rb:661:in `run_tasks_blocks'
/usr/local/bundle/gems/railties-7.0.2.2/lib/rails/application.rb:505:in `run_tasks_blocks'
/usr/local/bundle/gems/railties-7.0.2.2/lib/rails/engine.rb:464:in `load_tasks'
/usr/local/bundle/gems/railties-7.0.2.2/lib/rails/railtie.rb:224:in `public_send'
/usr/local/bundle/gems/railties-7.0.2.2/lib/rails/railtie.rb:224:in `method_missing'
/app/Rakefile:6:in `<top (required)>'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:23:in `load'
/usr/local/bundle/bin/rake:23:in `<main>'
```

**Comment by kzshantonu** [comment]
My bad, I missed a line in `.env`
